# Site settings
title: Leon Harrington
description: > # this means to ignore newlines until "baseurl:"
  Post-doctoral researcher at the Max Planck Institute for Biochemistry. Formerly University of Oxford. Interested in single-molecule detection and the biophysics and engineering of biological pattern formation.
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.leonharrington.com" # the base hostname & protocol for your site
twitter-username: drlharrington
# Build settings
markdown: kramdown
email: info@leonharrington.com
permalink: /blog/:year/:month/:day/:title

gems:
    - jekyll-sitemap